### ISSUE TITLE
Issue with new routing helper

### ISSUE THREAD

**Issue by tomkadwill** [lotus/helpers#15]
I'm having a problem using the new routing helper, introduced in https://github.com/lotus/helpers/pull/14. This is probably a lack in my understanding, if so, feel free to close.

I have the following view:

```
module Web
  require 'lotus/helpers'

  module Views
    class ApplicationLayout
      include Web::Layout
      include Lotus::Helpers

      def link_to_blog
        %(<a href="#{ routes.blog_path }">Blog</a>)
      end
    end
  end
end
```

This raises `NoMethodError: undefined method 'blog_path'`. However, if I change the view to use the `path` method, it works fine:

```
module Web
  require 'lotus/helpers'

  module Views
    class ApplicationLayout
      include Web::Layout
      include Lotus::Helpers

      def link_to_blog
        %(<a href="#{ routes.path(:blog) }">Blog</a>)
      end
    end
  end
end
```

Shouldn't the new routes helper be interchangeable with `routes.path`?

**Comment by jodosha** [comment]
Hey Tom, please make sure that your app uses lotus/lotus master, where there is the dynamic finders feature.

http://lucaguidi.com

**Comment by tomkadwill** [comment]
My bad, yep that works fine. Closing.
